# Generated by Django 2.1.2 on 2018-12-01 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_com', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_com', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_estado', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mas', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mas', models.CharField(max_length=30)),
                ('tamano_mas', models.IntegerField(default=0)),
                ('peso_mas', models.FloatField(default=0)),
                ('color_mas', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_res', models.DateField(verbose_name='Fecha Rescate')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('fec_nac', models.DateField(help_text='Fecha Nacimiento')),
                ('fono', models.PositiveIntegerField(help_text='Numero de telefono')),
                ('comuna', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('tp_vivienda', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id_reg', models.IntegerField(primary_key=True, serialize=False)),
                ('nomb_reg', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('tp_vivienda', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='reg_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.Regiones'),
        ),
    ]
